export enum SystemEvents {
  SCREEN_ENTER = "di_screen_enter",
  SCREEN_EXIT = "di_screen_exit",
  PAGE_VIEW = "di_pageview",
  SESSION_CREATED = "di_session_created",
  SESSION_END = "di_session_end"
}

export enum EventColumnIds {
  EVENT_ID = "di_event_id",
  EVENT_NAME = "di_event",
  EVENT_DISPLAY_NAME = "di_event_display_name",
  IS_SYSTEM_EVENT = "di_system_event",
  LIB_PLATFORM = "di_lib_platform",
  LIB_VERSION = "di_lib_version",
  TRACKING_ID = "di_tracking_id",
  SESSION_ID = "di_session_id",
  USER_ID = "di_user_id",
  SCREEN_NAME = "di_screen_name",
  CLIENT_IP = "di_client_ip",
  URL = "di_url",
  PATH = "di_path",
  QUERY_PARAMS = "di_url_params",
  REFERRER = "di_referrer",
  REFERRER_HOST = "di_referrer_host",
  REFERRER_QUERY_PARAMS = "di_referrer_params",
  REFERRER_SEARCH_ENGINE = "di_referrer_search_engine",
  SEARCH_ENGINE_KEYWORD = "di_referrer_search_keyword",
  OS = "di_os",
  OS_VERSION = "di_os_version",
  OS_VERSION_NAME = "di_os_version_name",
  BROWSER = "di_browser",
  BROWSER_VERSION = "di_browser_version",
  BROWSER_USER_AGENT = "di_browser_ua",
  BROWSER_PREFERRED_LANG = "di_browser_preffered_lang",
  BROWSER_LANGUAGES = "di_browser_languages",
  PLATFORM = "di_platform",
  PLATFORM_MODEL = "di_platform_model",
  PLATFORM_VENDOR = "di_platform_vendor",
  START_TIME = "di_start_time",
  DURATION = "di_duration",
  TIME = "di_time",
  TIME_MS = "di_time_ms"
}